import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import { checkContinuity } from "../src/continuity.js";
import {
  formatProjectReport,
  buildBook,
  computeWordCounts,
  createEntity,
  createStoryProject,
  exportManuscript,
  formatActionReport,
  migrateProject,
  projectReport,
  projectActions,
  reindexProject,
  removeEntity,
  renameEntity,
  scanProject,
  STORY_SCHEMA_VERSION,
  validateLinks,
  validateLinksOf,
  validateProject,
  validateProjectOf
} from "../src/story.js";
import { makeTempDir, writeMarkdown } from "./helpers.js";

function addStoryEntities(root) {
  writeMarkdown(path.join(root, "characters", "sera-voss.md"), `
name: "Sera Voss"
role: protagonist
status: alive
relationships:
  - character: kael-voss
    type: sibling
locations:
  - whispering-vale
`, "# Sera\n");
  writeMarkdown(path.join(root, "characters", "kael-voss.md"), `
name: "Kael Voss"
role: supporting
status: alive
relationships:
  - character: sera-voss
    type: sibling
locations:
  - whispering-vale
`, "# Kael\n");
  writeMarkdown(path.join(root, "worldbuilding", "locations", "whispering-vale.md"), `
name: "Whispering Vale"
type: wilderness
region: North
notable-characters:
  - sera-voss
  - kael-voss
`, "# Vale\n");
  writeMarkdown(path.join(root, "worldbuilding", "systems", "ember-magic.md"), `
name: "Ember Magic"
type: magic
`, "# Ember\n");
  writeMarkdown(path.join(root, "plot", "arcs", "reclamation.md"), `
name: "Reclamation"
type: main
status: planned
characters:
  - sera-voss
themes:
  - redemption
`, "# Arc\n");
  writeMarkdown(path.join(root, "chapters", "chapter-01.md"), `
title: "The Ember Wakes"
number: 1
pov: sera-voss
locations:
  - whispering-vale
characters:
  - sera-voss
arcs-advanced:
  - reclamation
status: draft
word-count: 0
`, "# Chapter 1\n\n## Outline\n\n1. Beat\n\n---\n\nSera returned home.");
  writeMarkdown(path.join(root, "scenes", "chapter-01-scene-01.md"), `
title: "Sera Returns"
chapter: chapter-01
scene: 1
pov: sera-voss
location: whispering-vale
characters:
  - sera-voss
arcs-advanced:
  - reclamation
status: draft
state-changes: []
`, "# Sera Returns\n");
}

describe("story project operations", () => {
  test("creates, scans, reindexes, counts, validates, links, and exports a story project", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({
      cwd,
      title: "The Last Ember",
      genre: "fantasy",
      subGenre: "epic",
      settingEra: "medieval",
      themes: ["redemption", "legacy"],
      pov: "third-person-limited",
      tense: "past",
      synopsis: "Sera returns.",
      force: false
    });

    expect(created.storyId).toBe("the-last-ember");
    expect(fs.existsSync(path.join(created.root, "story.md"))).toBe(true);
    expect(scanProject(created.root).story.data["schema-version"]).toBe(STORY_SCHEMA_VERSION);
    addStoryEntities(created.root);

    const project = scanProject(created.root);
    expect(project.characters.map((item) => item.id)).toEqual(["kael-voss", "sera-voss"]);
    expect(project.scenes.map((item) => item.id)).toEqual(["chapter-01-scene-01"]);
    expect(project.chapters[0].wordCount).toBe(3);

    const reindexed = reindexProject(created.root);
    expect(reindexed.changed.map((file) => path.basename(file))).toContain("_index.md");
    expect(fs.readFileSync(path.join(created.root, "characters", "_index.md"), "utf8")).toContain("[sera-voss](sera-voss.md)");
    expect(fs.readFileSync(path.join(created.root, "worldbuilding", "_index.md"), "utf8")).toContain("[whispering-vale](locations/whispering-vale.md)");
    expect(fs.readFileSync(path.join(created.root, "plot", "_index.md"), "utf8")).toContain("[reclamation](arcs/reclamation.md)");
    expect(fs.readFileSync(path.join(created.root, "scenes", "_index.md"), "utf8")).toContain("[chapter-01-scene-01](chapter-01-scene-01.md)");

    const counts = computeWordCounts(created.root, { write: true });
    expect(counts).toEqual({
      chapters: [{ number: 1, title: "The Ember Wakes", file: path.join("chapters", "chapter-01.md"), wordCount: 3 }],
      total: 3
    });
    expect(fs.readFileSync(path.join(created.root, "chapters", "chapter-01.md"), "utf8")).toContain("word-count: 3");

    expect(validateProject(created.root).ok).toBe(true);
    expect(validateLinks(created.root)).toEqual({ ok: true, errors: [], warnings: [] });

    const exported = exportManuscript(created.root, { out: "book.md" });
    expect(exported.chapters).toBe(1);
    expect(fs.readFileSync(exported.outFile, "utf8")).toContain("# Chapter 1: The Ember Wakes\n\nSera returned home.");

    const built = buildBook(created.root);
    expect(built).toEqual({
      outFile: path.join(created.root, "dist", "the-last-ember.md"),
      chapters: 1,
      format: "markdown"
    });
    expect(fs.readFileSync(built.outFile, "utf8")).toContain("Generated by story build");
  });

  test("builds a project report", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Reported Story", force: false });
    addStoryEntities(created.root);
    computeWordCounts(created.root, { write: true });

    const report = projectReport(created.root);
    expect(report.counts).toEqual({
      characters: 2,
      locations: 1,
      systems: 1,
      factions: 0,
      artifacts: 0,
      arcs: 1,
      chapters: 1,
      scenes: 1,
      questions: 0,
      promises: 0,
      clues: 0,
      glossaryTerms: 0,
      research: 0,
      words: 3
    });
    expect(report.validation.ok).toBe(true);
    expect(report.links.ok).toBe(true);

    const formatted = formatProjectReport(report);
    expect(formatted).toContain("# Reported Story");
    expect(formatted).toContain(`Schema version: ${STORY_SCHEMA_VERSION}`);
    expect(formatted).toContain("- 1. The Ember Wakes (draft, 3 words, POV: sera-voss)");
    expect(formatted).toContain("- Validate: ok (0 errors, 0 warnings)");

    const empty = formatProjectReport(projectReport(createStoryProject({ cwd, title: "Empty Report", force: false }).root));
    expect(empty).toContain("Chapters:\n- None");
    expect(empty).toContain("Arcs:\n- None");
  });

  test("exports natural chapters without duplicating a leading H1 heading", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Harbor Example", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: "The Tide Board"
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: complete
word-count: 0
`, "# Chapter 1: The Tide Board\n\nProse starts here.");

    expect(scanProject(created.root).chapters[0].wordCount).toBe(3);

    const exported = exportManuscript(created.root, { out: "book.md" });
    const exportedText = fs.readFileSync(exported.outFile, "utf8");
    expect(exportedText.match(/^# Chapter 1: The Tide Board$/gm)?.length).toBe(1);
    expect(exportedText).toContain("# Chapter 1: The Tide Board\n\nProse starts here.");

    const built = buildBook(created.root);
    const builtText = fs.readFileSync(built.outFile, "utf8");
    expect(builtText.match(/^# Chapter 1: The Tide Board$/gm)?.length).toBe(1);
    expect(builtText).toContain("# Chapter 1: The Tide Board\n\nProse starts here.");
  });

  test("supports forced init, default metadata, and unchanged reindex", () => {
    const cwd = makeTempDir();
    const first = createStoryProject({ cwd, title: "Quiet Stars", force: false });
    expect(() => createStoryProject({ cwd, title: "Quiet Stars", force: false })).toThrow("already exists");
    const second = createStoryProject({ cwd, title: "Quiet Stars", force: true, themes: [] });
    expect(second.root).toBe(first.root);
    expect(reindexProject(second.root).changed).toEqual([]);
  });

  test("refuses to overwrite maintenance outputs through symlinks", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Symlink Trap", force: false });
    const outside = path.join(cwd, "outside.md");
    fs.writeFileSync(outside, "outside sentinel", "utf8");

    const chapterIndex = path.join(created.root, "chapters", "_index.md");
    fs.rmSync(chapterIndex);
    fs.symlinkSync(outside, chapterIndex);

    expect(() => reindexProject(created.root)).toThrow("Refusing to write through symlink");
    expect(fs.readFileSync(outside, "utf8")).toBe("outside sentinel");
  });

  test("refuses to write project files through symlinked directories", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Symlink Directory", force: false });
    const outsideChapters = path.join(cwd, "outside-chapters");
    fs.mkdirSync(outsideChapters);

    fs.rmSync(path.join(created.root, "chapters"), { recursive: true, force: true });
    fs.symlinkSync(outsideChapters, path.join(created.root, "chapters"), "dir");

    expect(() => createEntity(created.root, { kind: "chapter", name: "Escaped", number: 1 })).toThrow("symlinked project directory");
    expect(fs.existsSync(path.join(outsideChapters, "chapter-01.md"))).toBe(false);
  });

  test("refuses unsafe project directories reached during scans", () => {
    const cwd = makeTempDir();
    const fileDirectory = createStoryProject({ cwd, title: "File Directory", force: false });
    fs.rmSync(path.join(fileDirectory.root, "characters"), { recursive: true, force: true });
    fs.writeFileSync(path.join(fileDirectory.root, "characters"), "not a directory", "utf8");

    expect(() => scanProject(fileDirectory.root)).toThrow("Project path is not a directory");

    const escapedDirectory = createStoryProject({ cwd, title: "Escaped Directory", force: false });
    const outsideWorld = path.join(cwd, "outside-world");
    fs.mkdirSync(path.join(outsideWorld, "locations"), { recursive: true });
    fs.rmSync(path.join(escapedDirectory.root, "worldbuilding"), { recursive: true, force: true });
    fs.symlinkSync(outsideWorld, path.join(escapedDirectory.root, "worldbuilding"), "dir");

    expect(() => scanProject(escapedDirectory.root)).toThrow("project directory outside root");
  });

  test("rejects traversal ids before rename, remove, and scene creation", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Traversal IDs", force: false });
    const victim = path.join(cwd, "victim.md");
    fs.writeFileSync(victim, "victim sentinel", "utf8");

    expect(() => removeEntity(created.root, { kind: "character", id: "../../victim" })).toThrow("must be a kebab-case id");
    expect(() => renameEntity(created.root, { kind: "character", id: "../../victim", name: "Moved Victim" })).toThrow("must be a kebab-case id");
    expect(() => createEntity(created.root, { kind: "scene", name: "Escaped Scene", chapter: "../../victim" })).toThrow("chapter id must be a kebab-case id");
    expect(fs.readFileSync(victim, "utf8")).toBe("victim sentinel");
    expect(fs.existsSync(path.join(cwd, "victim-scene-01.md"))).toBe(false);
  });

  test("rejects relative export outputs outside the project root", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Output Traversal", force: false });
    addStoryEntities(created.root);

    expect(() => exportManuscript(created.root, { out: "../outside.md" })).toThrow("outside project root");
    expect(fs.existsSync(path.join(cwd, "outside.md"))).toBe(false);
  });

  test("rejects outputs through symlinked parent directories", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Output Symlink", force: false });
    addStoryEntities(created.root);
    const outsideDist = path.join(cwd, "outside-dist");
    fs.mkdirSync(outsideDist);
    fs.symlinkSync(outsideDist, path.join(created.root, "dist"), "dir");

    expect(() => buildBook(created.root)).toThrow("project path outside root");
    expect(fs.existsSync(path.join(outsideDist, "output-symlink.md"))).toBe(false);
  });

  test("recreates missing registry files without leaving the project root", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Missing Registry", force: false });
    const registry = path.join(created.root, "characters", "_index.md");
    fs.rmSync(registry);

    expect(reindexProject(created.root).changed).toContain(registry);
    expect(fs.readFileSync(registry, "utf8")).toContain("type: character-registry");
  });

  test("reports missing structure, frontmatter fields, registry warnings, word-count warnings, and link errors", () => {
    const cwd = makeTempDir();
    expect(validateProject(cwd).errors).toContain("Missing required path: story.md");

    const created = createStoryProject({ cwd, title: "Broken Links", force: false });
    writeMarkdown(path.join(created.root, "characters", "orphan.md"), `
name: Orphan
role: supporting
status: alive
relationships:
  - character: missing-person
    type: friend
locations:
  - missing-place
`, "# Orphan");
    writeMarkdown(path.join(created.root, "worldbuilding", "locations", "empty.md"), `
name: Empty
type: ruins
notable-characters:
  - missing-person
`, "# Empty");
    writeMarkdown(path.join(created.root, "plot", "arcs", "bad-arc.md"), `
name: Bad Arc
type: main
status: planned
characters:
  - missing-person
`, "# Arc");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: "Bad Chapter"
number: 2
pov: orphan
locations:
  - missing-place
characters:
  - missing-person
arcs-advanced:
  - missing-arc
status: draft
word-count: 10
`, "## Chapter Text\n\nTwo words.");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(true);
    expect(validation.warnings.some((warning) => warning.includes("registry link"))).toBe(true);
    expect(validation.warnings.some((warning) => warning.includes("declares 10 words"))).toBe(true);

    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("missing character missing-person");
    expect(links.errors.join("\n")).toContain("missing location missing-place");
    expect(links.errors.join("\n")).toContain("missing arc missing-arc");
  });

  test("reports missing backlinks and supports missing directories plus filename chapter numbers", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Backlink Gaps", force: false });
    fs.rmSync(path.join(created.root, "plot", "arcs"), { recursive: true, force: true });
    writeMarkdown(path.join(created.root, "characters", "sera-voss.md"), `
name: "Sera Voss"
role: protagonist
status: alive
relationships:
  - character: kael-voss
    type: sibling
locations:
  - whispering-vale
`, "# Sera");
    writeMarkdown(path.join(created.root, "characters", "kael-voss.md"), `
name: "Kael Voss"
role: supporting
status: alive
locations: []
`, "# Kael");
    writeMarkdown(path.join(created.root, "characters", "maren.md"), `
name: Maren
role: antagonist
status: alive
locations: []
`, "# Maren");
    writeMarkdown(path.join(created.root, "worldbuilding", "locations", "whispering-vale.md"), `
name: "Whispering Vale"
type: wilderness
notable-characters:
  - maren
`, "# Vale");
    writeMarkdown(path.join(created.root, "chapters", "chapter-07.md"), `
title: Seven
pov: sera-voss
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nSeven words here.");

    const project = scanProject(created.root);
    expect(project.arcs).toEqual([]);
    expect(project.chapters[0].number).toBe(7);

    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("relationship to kael-voss is missing backlink");
    expect(links.errors.join("\n")).toContain("location whispering-vale is missing notable-character backlink");
    expect(links.errors.join("\n")).toContain("notable character maren is missing location backlink");
  });

  test("sorts multiple chapters by number and then filename", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Chapter Order", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-10.md"), `
title: Ten
number: 10
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nTen.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: Two
number: 2
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nTwo.");

    expect(scanProject(created.root).chapters.map((chapter) => chapter.number)).toEqual([2, 10]);
  });

  test("reports missing required frontmatter fields and empty export", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "No Chapters", force: false });
    writeMarkdown(path.join(created.root, "characters", "nameless.md"), `
name: Nameless
role: supporting
`, "# Nameless");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors).toContain(`characters${path.sep}nameless.md is missing frontmatter field status`);
    expect(() => exportManuscript(created.root)).toThrow("No chapters found to export");
  });

  test("reports schema and frontmatter contract violations", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Strict Format", force: false });
    fs.writeFileSync(
      path.join(created.root, "story.md"),
      fs.readFileSync(path.join(created.root, "story.md"), "utf8")
        .replace("schema-version: 1", "schema-version: 99")
        .replace("schema-version: 2", "schema-version: 99")
        .replace("genre: fiction", "genre:\n  - fiction")
        .replace("themes:\n  - change", "themes: none")
        .replace("status: planning", "status: unknown-stage"),
      "utf8"
    );
    fs.writeFileSync(
      path.join(created.root, "characters", "_index.md"),
      fs.readFileSync(path.join(created.root, "characters", "_index.md"), "utf8")
        .replace("type: character-registry", "type: wrong-registry")
        .replace("story: strict-format", "story: wrong-story"),
      "utf8"
    );
    writeMarkdown(path.join(created.root, "characters", "Bad Name.md"), `
name:
  - Bad Name
role: cameo
status: alive
aliases:
  - ""
relationships:
  - character: Not Kebab
    type: parent
  - not-object
  - type: friend
  - character: missing-person
locations: none
`, "# Bad");
    writeMarkdown(path.join(created.root, "characters", "parent-one.md"), `
name: Parent One
role: supporting
status: alive
relationships:
  - character: child-one
    type: parent
locations: []
`, "# Parent");
    writeMarkdown(path.join(created.root, "characters", "child-one.md"), `
name: Child One
role: supporting
status: alive
relationships:
  - character: parent-one
    type: parent
locations: []
`, "# Child");
    writeMarkdown(path.join(created.root, "characters", "bad-relationships.md"), `
name: Bad Relationships
role: supporting
status: alive
relationships: none
locations: []
`, "# Bad Relationships");
    writeMarkdown(path.join(created.root, "worldbuilding", "systems", "bad-system.md"), `
name: Bad System
type: technology
prevalence:
  - common
`, "# Bad System");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 2
pov: missing-person
locations: []
characters: []
arcs-advanced: []
status: invalid
word-count: many
`, "## Chapter Text\n\nWords.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-00.md"), `
title: Zero
number: 0
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 1
`, "## Chapter Text\n\nZero.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: Two
number: 2
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 1
`, "## Chapter Text\n\nTwo.");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors.join("\n")).toContain(`story.md schema-version must be ${STORY_SCHEMA_VERSION}`);
    expect(validation.errors.join("\n")).toContain("story.md frontmatter field genre must be a scalar");
    expect(validation.errors.join("\n")).toContain("story.md frontmatter field themes must be a list");
    expect(validation.errors.join("\n")).toContain("story.md frontmatter field status has unsupported value unknown-stage");
    expect(validation.errors.join("\n")).toContain("characters/_index.md type must be character-registry");
    expect(validation.errors.join("\n")).toContain("characters/_index.md story must be strict-format");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md filename id must be kebab-case");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field name must be a scalar");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field role has unsupported value cameo");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field aliases must contain only non-empty strings");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field locations must be a list");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md relationship character Not Kebab must be kebab-case");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md frontmatter field relationships must contain objects");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md relationship is missing character");
    expect(validation.errors.join("\n")).toContain("characters/Bad Name.md relationship to missing-person is missing type");
    expect(validation.errors.join("\n")).toContain("characters/bad-relationships.md frontmatter field relationships must be a list");
    expect(validation.errors.join("\n")).toContain("worldbuilding/systems/bad-system.md frontmatter field prevalence must be a scalar");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-00.md filename must match chapter-{NN}.md");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-00.md number must be greater than 0");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md frontmatter field word-count must be an integer");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md number must match filename chapter number 1");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-02.md duplicates chapter number 2");

    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("references missing POV character missing-person");
    expect(links.errors.join("\n")).toContain("relationship parent to child-one expects backlink type child, got parent");
  });

  test("creates, renames, removes, migrates, and recommends next actions", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Helper Story", force: false });
    const character = createEntity(created.root, { kind: "character", name: "Mira Sol", role: "protagonist" });
    const location = createEntity(created.root, { kind: "location", name: "Glass Harbor", type: "city", character: "mira-sol" });
    const system = createEntity(created.root, { kind: "system", name: "Tide Magic", type: "magic" });
    const faction = createEntity(created.root, { kind: "faction", name: "Harbor Guild", type: "guild", member: "mira-sol", location: "glass-harbor" });
    const artifact = createEntity(created.root, { kind: "artifact", name: "Tide Key", owner: "harbor-guild", location: "glass-harbor" });
    const arc = createEntity(created.root, { kind: "arc", name: "Find The Tide Key", type: "main", character: "mira-sol" });
    const chapter = createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1, pov: "mira-sol", location: "glass-harbor", character: "mira-sol", arc: "find-the-tide-key" });
    expect(chapter.id).toBe("chapter-01");
    const scene = createEntity(created.root, { kind: "scene", name: "At The Pier", chapter: "chapter-01", scene: 1, pov: "mira-sol", location: "glass-harbor", character: "mira-sol", arc: "find-the-tide-key" });
    const nextScene = createEntity(created.root, { kind: "scene", name: "Second Beat", chapter: "chapter-01" });
    const question = createEntity(created.root, { kind: "question", name: "Who hid the key?", introduced: "chapter-01", character: "mira-sol" });
    const promise = createEntity(created.root, { kind: "promise", name: "The key opens the reef vault", planted: "chapter-01", arc: "find-the-tide-key", character: "mira-sol" });
    const term = createEntity(created.root, { kind: "term", name: "Reef Vault", category: "place", alias: "vault" });

    expect(character.id).toBe("mira-sol");
    expect(location.id).toBe("glass-harbor");
    expect(system.id).toBe("tide-magic");
    expect(faction.id).toBe("harbor-guild");
    expect(artifact.id).toBe("tide-key");
    expect(arc.id).toBe("find-the-tide-key");
    expect(chapter.id).toBe("chapter-01");
    expect(scene.id).toBe("chapter-01-scene-01");
    expect(nextScene.id).toBe("chapter-01-scene-02");
    expect(question.id).toBe("who-hid-the-key");
    expect(promise.id).toBe("the-key-opens-the-reef-vault");
    expect(term.id).toBe("reef-vault");
    const activeActions = formatActionReport(projectActions(created.root));
    expect(activeActions).toContain("Track open questions");
    expect(activeActions).toContain("Review promises and payoffs");

    const renamed = renameEntity(created.root, { kind: "character", id: "mira-sol", name: "Mira Vale" });
    expect(renamed.id).toBe("mira-vale");
    expect(fs.readFileSync(path.join(created.root, "chapters", "chapter-01.md"), "utf8")).toContain("mira-vale");

    const removed = removeEntity(created.root, { kind: "promise", id: "the-key-opens-the-reef-vault" });
    expect(removed.id).toBe("the-key-opens-the-reef-vault");
    expect(fs.existsSync(path.join(created.root, "continuity", "promises", "the-key-opens-the-reef-vault.md"))).toBe(false);

    const actions = projectActions(created.root);
    expect(formatActionReport(actions)).toContain("Draft chapter 2");
    expect(formatActionReport({
      title: "Empty",
      validation: { ok: true, errors: [], warnings: [] },
      links: { ok: true, errors: [], warnings: [] },
      continuity: { ok: true, errors: [], warnings: [] },
      actions: []
    })).toContain("No actions found");

    fs.rmSync(path.join(created.root, "glossary"), { recursive: true, force: true });
    fs.writeFileSync(
      path.join(created.root, "story.md"),
      fs.readFileSync(path.join(created.root, "story.md"), "utf8").replace("schema-version: 2", "schema-version: 1"),
      "utf8"
    );
    const migrated = migrateProject(created.root);
    expect(migrated.changed.length).toBeGreaterThan(0);
    expect(scanProject(created.root).story.data["schema-version"]).toBe(STORY_SCHEMA_VERSION);
  });

  test("add chapter serializes date and time options into frontmatter", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Chronology API", force: false });
    const chapter = createEntity(created.root, { kind: "chapter", name: "Harvest", number: 1, date: "2026-03-01", time: "09:30" });

    const raw = fs.readFileSync(chapter.file, "utf8");
    expect(raw).toContain("date: 2026-03-01");
    expect(raw).toContain("time: 09:30");
    const scanned = scanProject(created.root).chapters.find((entry) => entry.id === "chapter-01");
    expect(scanned.date).toBe("2026-03-01");
    expect(scanned.time).toBe("09:30");
  });

  test("add scene writes travel-hours and rejects non-numeric values", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Travel", force: false });
    createEntity(created.root, { kind: "chapter", name: "One", number: 1 });
    const scene = createEntity(created.root, { kind: "scene", name: "Road", chapter: "chapter-01", "travel-hours": 3 });

    const raw = fs.readFileSync(scene.file, "utf8");
    expect(raw).toContain("travel-hours: 3");
    expect(scanProject(created.root).scenes.find((entry) => entry.id === "chapter-01-scene-01").travelHours).toBe(3);
    expect(() => createEntity(created.root, { kind: "scene", name: "Bad Road", chapter: "chapter-01", "travel-hours": "nonsense" }))
      .toThrow("travel-hours must be a number");
  });

  test("accepts abandoned and cut statuses from the discovery-drafting cut-thread convention", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Cut Statuses", force: false });
    const root = created.root;
    writeMarkdown(path.join(root, "continuity", "promises", "dead-promise.md"), `
title: Dead Promise
status: abandoned
`, "# Dead Promise\n");
    writeMarkdown(path.join(root, "continuity", "questions", "dead-question.md"), `
title: Dead Question
status: abandoned
`, "# Dead Question\n");
    writeMarkdown(path.join(root, "characters", "cut-character.md"), `
name: Cut Character
role: supporting
status: cut
`, "# Cut Character\n");

    const validation = validateProject(root);
    expect(validation.errors.filter((error) => /dead-promise|dead-question|cut-character/.test(error))).toEqual([]);
  });

  test("abandoned threads are skipped by continuity ordering checks", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Abandoned Ordering", force: false });
    const root = created.root;
    for (let number = 1; number <= 3; number += 1) {
      writeMarkdown(path.join(root, "chapters", `chapter-0${number}.md`), `
title: Chapter ${number}
number: ${number}
status: draft
word-count: 0
`, "## Chapter Text\n\nWords here.\n");
    }
    writeMarkdown(path.join(root, "continuity", "promises", "dead-promise.md"), `
title: Dead Promise
status: abandoned
planted: chapter-03
payoff: chapter-01
`, "# Dead Promise\n");

    const continuity = checkContinuity(scanProject(root));
    expect(continuity.errors.filter((error) => error.includes("dead-promise"))).toEqual([]);
  });

  test("rejects malformed scene metadata types", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Scene Types", force: false });
    const root = created.root;
    writeMarkdown(path.join(root, "scenes", "chapter-01-scene-01.md"), `
title: Bad Scene
chapter: chapter-01
scene: 1
status: draft
travel-hours: nonsense
sequel: "false"
date:
  - 2026-01-01
`, "# Bad Scene\n");

    const validation = validateProject(root);
    const errors = validation.errors.join("\n");
    expect(validation.ok).toBe(false);
    expect(errors).toContain("frontmatter field travel-hours must be a number");
    expect(errors).toContain("frontmatter field sequel must be a boolean");
    expect(errors).toContain("frontmatter field date must be a scalar");
  });

  test("warns when a clue file is missing from the clue registry", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Clue Registry", force: false });
    const root = created.root;
    writeMarkdown(path.join(root, "continuity", "clues", "orphan-clue.md"), `
title: Orphan Clue
status: planned
`, "# Orphan Clue\n");

    const validation = validateProject(root);
    expect(validation.warnings).toContain("continuity/clues/_index.md is missing registry link ](orphan-clue.md)");
  });

  test("remove scrubs references without rewriting untouched files", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Remove Touch", force: false });
    createEntity(created.root, { kind: "character", name: "Keeper", role: "supporting" });
    createEntity(created.root, { kind: "promise", name: "Old Setup", character: "keeper" });
    const storyPath = path.join(created.root, "story.md");
    fs.writeFileSync(storyPath, fs.readFileSync(storyPath, "utf8").replace("title:", "# hand-written note\ntitle:"), "utf8");
    const annotated = fs.readFileSync(storyPath, "utf8");

    removeEntity(created.root, { kind: "character", id: "keeper" });

    expect(fs.readFileSync(storyPath, "utf8")).toBe(annotated);
    expect(fs.readFileSync(path.join(created.root, "continuity", "promises", "old-setup.md"), "utf8")).not.toContain("keeper");
  });

  test("remove clears only reference fields, never unrelated values that equal the id", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Remove Enum", force: false });
    createEntity(created.root, { kind: "artifact", name: "Lost", status: "hidden" });
    createEntity(created.root, { kind: "artifact", name: "Map", status: "lost" });
    createEntity(created.root, { kind: "character", name: "Keeper", role: "supporting" });
    createEntity(created.root, { kind: "character", name: "Rival", role: "supporting" });
    const keeperPath = path.join(created.root, "characters", "keeper.md");
    writeMarkdown(keeperPath, `
name: Keeper
role: supporting
status: alive
relationships:
  - character: rival
    type: rival
  - character: lost
    type: ally
locations: []
`, "# Keeper");

    createEntity(created.root, { kind: "chapter", name: "One", number: 1, pov: "rival", character: "rival,keeper" });

    removeEntity(created.root, { kind: "artifact", id: "lost" });

    expect(fs.readFileSync(path.join(created.root, "worldbuilding", "artifacts", "map.md"), "utf8")).toContain("status: lost");
    const keeper = fs.readFileSync(keeperPath, "utf8");
    expect(keeper).toContain("  - character: rival\n    type: rival");
    // relationships point at characters, so removing the artifact `lost` leaves them alone
    expect(keeper).toContain("character: lost");

    removeEntity(created.root, { kind: "character", id: "rival" });

    const chapter = fs.readFileSync(path.join(created.root, "chapters", "chapter-01.md"), "utf8");
    expect(chapter).toContain('pov: ""');
    expect(chapter).toContain("characters:\n  - keeper\n");
    expect(fs.readFileSync(keeperPath, "utf8")).toContain("relationships:\n  - character: lost\n    type: ally\nlocations");
  });

  test("remove drops object-state rows for a removed artifact", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Remove Artifact Row", force: false });
    createEntity(created.root, { kind: "location", name: "Vault", type: "building" });
    createEntity(created.root, { kind: "artifact", name: "Key", status: "hidden" });
    createEntity(created.root, { kind: "artifact", name: "Map", status: "hidden" });
    const statePath = path.join(created.root, "continuity", "state.md");
    fs.writeFileSync(statePath, fs.readFileSync(statePath, "utf8").replace(
      "object-state: []",
      "object-state:\n  - artifact: key\n    location: vault\n  - artifact: map\n    location: vault"
    ), "utf8");

    removeEntity(created.root, { kind: "artifact", id: "key" });

    const state = fs.readFileSync(statePath, "utf8");
    expect(state).not.toContain("artifact: key");
    expect(state).not.toContain('artifact: ""');
    expect(state).toContain("  - artifact: map\n    location: vault");
  });

  test("rename updates frontmatter references and link targets but leaves prose alone", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Rename Prose", force: false });
    createEntity(created.root, { kind: "location", name: "Port", type: "city" });
    createEntity(created.root, { kind: "artifact", name: "Chart", location: "port" });
    createEntity(created.root, { kind: "chapter", name: "Docks", number: 1, location: "port" });
    const chapterPath = path.join(created.root, "chapters", "chapter-01.md");
    fs.appendFileSync(chapterPath, "The port was quiet. [Port](../worldbuilding/locations/port.md)\n", "utf8");
    fs.writeFileSync(path.join(created.root, "README.md"), "No frontmatter here, port.\n", "utf8");

    renameEntity(created.root, { kind: "location", id: "port", name: "Harbor" });

    const chapterText = fs.readFileSync(chapterPath, "utf8");
    expect(chapterText).toContain("  - harbor");
    expect(chapterText).toContain("The port was quiet. [Port](../worldbuilding/locations/harbor.md)");
    expect(fs.readFileSync(path.join(created.root, "worldbuilding", "artifacts", "chart.md"), "utf8")).toContain("location: harbor");
    expect(fs.readFileSync(path.join(created.root, "README.md"), "utf8")).toBe("No frontmatter here, port.\n");
    expect(validateLinks(created.root)).toEqual({ ok: true, errors: [], warnings: [] });
  });

  test("rejects ids and numbers that cannot name a file", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Bad Ids", force: false });
    expect(() => createEntity(created.root, { kind: "character", name: "???" })).toThrow("Cannot derive a kebab-case id");
    expect(() => createEntity(created.root, { kind: "chapter", name: "Two", number: "abc" })).toThrow("chapter number must be a positive integer");
    expect(() => createEntity(created.root, { kind: "scene", name: "Beat", chapter: "chapter-01", scene: 0 })).toThrow("scene number must be a positive integer");
    expect(fs.readdirSync(path.join(created.root, "chapters"))).toEqual(["_index.md"]);
    expect(() => scanProject(path.join(cwd, "nowhere"))).toThrow("is not a story project: missing story.md");
  });

  test("wordcount --write leaves chapters with current counts untouched", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Count Touch", force: false });
    const chapterPath = path.join(created.root, "chapters", "chapter-01.md");
    writeMarkdown(chapterPath, `
# reviewer note
title: One
number: 1
status: draft
word-count: 2
`, "## Chapter Text\n\nOne two.");
    const before = fs.readFileSync(chapterPath, "utf8");

    computeWordCounts(created.root, { write: true });

    expect(fs.readFileSync(chapterPath, "utf8")).toBe(before);
  });

  test("renders markdown emphasis as italic and bold runs in epub and docx", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Emphasis Build", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
status: draft
word-count: 0
`, "## Chapter Text\n\nShe *whispered* the **name** and _left_.\n\n* * *\n\nsnake_case_word stays.");

    const epub = fs.readFileSync(buildBook(created.root, { format: "epub" }).outFile).toString("utf8");
    expect(epub).toContain("<p>She <em>whispered</em> the <strong>name</strong> and <em>left</em>.</p>");
    expect(epub).toContain("<p>* * *</p>");
    expect(epub).toContain("<p>snake_case_word stays.</p>");

    const docx = fs.readFileSync(buildBook(created.root, { format: "docx" }).outFile).toString("utf8");
    expect(docx).toContain('<w:r><w:t xml:space="preserve">She </w:t></w:r><w:r><w:rPr><w:i/></w:rPr><w:t xml:space="preserve">whispered</w:t></w:r>');
    expect(docx).toContain('<w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">name</w:t></w:r>');
  });

  test("rename leaves overlapping entity ids and prose words intact", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Rename Overlap", force: false });
    createEntity(created.root, { kind: "character", name: "Mara", role: "protagonist" });
    createEntity(created.root, { kind: "character", name: "Mara Quill", role: "supporting" });
    createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1, pov: "mara-quill", character: "mara-quill,mara" });
    const chapterPath = path.join(created.root, "chapters", "chapter-01.md");
    fs.appendFileSync(chapterPath, "The marathon passed mara on the docks. See [mara](../characters/mara.md) and [Mara](../characters/mara.md).\n", "utf8");

    renameEntity(created.root, { kind: "character", id: "mara", name: "Tess" });

    const chapterText = fs.readFileSync(chapterPath, "utf8");
    expect(chapterText).toContain("pov: mara-quill");
    expect(chapterText).toContain("- tess");
    expect(chapterText).toContain("The marathon passed mara on the docks. See [tess](../characters/tess.md) and [Mara](../characters/tess.md).");
    expect(fs.existsSync(path.join(created.root, "characters", "mara-quill.md"))).toBe(true);
    expect(validateLinks(created.root)).toEqual({ ok: true, errors: [], warnings: [] });
  });

  test("scene rename keeps the filename and only updates the title", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Scene Rename", force: false });
    createEntity(created.root, { kind: "chapter", name: "One", number: 1 });
    const scene = createEntity(created.root, { kind: "scene", name: "Opening", chapter: "chapter-01", scene: 1 });
    const renamed = renameEntity(created.root, { kind: "scene", id: scene.id, name: "The Pier" });

    expect(renamed.id).toBe("chapter-01-scene-01");
    expect(fs.existsSync(path.join(created.root, "scenes", "chapter-01-scene-01.md"))).toBe(true);
    expect(fs.readFileSync(renamed.file, "utf8")).toContain("title: The Pier");
    expect(validateProject(created.root).ok).toBe(true);
  });

  test("rename rewrites anchors on the old file and leaves overlapping ids alone", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Anchor Rename", force: false });
    createEntity(created.root, { kind: "character", name: "Mara", role: "protagonist" });
    createEntity(created.root, { kind: "character", name: "Mara Quill", role: "supporting" });
    const chapter = createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1 });
    fs.appendFileSync(chapter.file, "See [mara](../characters/mara-quill.md) and [mara](../characters/mara.md#intro) and [mara](../characters/mara.md?ref=1).\n", "utf8");

    renameEntity(created.root, { kind: "character", id: "mara", name: "Tess" });

    const chapterText = fs.readFileSync(chapter.file, "utf8");
    expect(chapterText).toContain("[mara](../characters/mara-quill.md)");
    expect(chapterText).toContain("[tess](../characters/tess.md#intro)");
    expect(chapterText).toContain("[tess](../characters/tess.md?ref=1)");
  });

  test("rename leaves external URLs that end in the old filename alone", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "External Rename", force: false });
    createEntity(created.root, { kind: "character", name: "Mara", role: "protagonist" });
    const chapter = createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1 });
    fs.appendFileSync(chapter.file, "See [mara](https://example.test/mara.md#s), [mara](//cdn.example.test/mara.md), and [mara](../characters/mara.md).\n", "utf8");

    renameEntity(created.root, { kind: "character", id: "mara", name: "Tess" });

    const chapterText = fs.readFileSync(chapter.file, "utf8");
    expect(chapterText).toContain("[mara](https://example.test/mara.md#s)");
    expect(chapterText).toContain("[mara](//cdn.example.test/mara.md)");
    expect(chapterText).toContain("[tess](../characters/tess.md)");
  });

  test("remove clears since and learned-in without dropping the rest of the row", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Scrub Since", force: false });
    createEntity(created.root, { kind: "chapter", name: "One", number: 1 });
    createEntity(created.root, { kind: "character", name: "Ada", role: "protagonist" });
    createEntity(created.root, { kind: "artifact", name: "Key", type: "object" });
    const statePath = path.join(created.root, "continuity", "state.md");
    const state = fs.readFileSync(statePath, "utf8");
    fs.writeFileSync(statePath, state.replace(`character-state: []
object-state: []
knowledge-state: []`, `character-state: []
knowledge-state:
  - character: ada
    knows: the vault is open
    learned-in: chapter-01
object-state:
  - artifact: key
    since: chapter-01
    location: vault`), "utf8");

    removeEntity(created.root, { kind: "chapter", id: "chapter-01" });

    const next = fs.readFileSync(statePath, "utf8");
    expect(next).toContain("knows: the vault is open");
    expect(next).toContain('learned-in: ""');
    expect(next).toContain("artifact: key");
    expect(next).toContain('since: ""');
  });

  test("rejects enum values and tenses that validate would reject", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Enums", force: false });
    expect(() => createEntity(created.root, { kind: "scene", name: "Beat", chapter: "chapter-01", scene: 1, status: "bogus" })).toThrow("Unsupported scene status");
    expect(() => createEntity(created.root, { kind: "faction", name: "Guild", status: "bogus" })).toThrow("Unsupported faction status");
    expect(() => createEntity(created.root, { kind: "arc", name: "Arc", status: "bogus" })).toThrow("Unsupported arc status");
    expect(() => createEntity(created.root, { kind: "artifact", name: "Relic", status: "bogus" })).toThrow("Unsupported artifact status");
    expect(() => createStoryProject({ cwd, title: "Bad Tense", tense: "bogus" })).toThrow("Unsupported tense");
    createEntity(created.root, { kind: "chapter", name: "Dated", number: 1, date: "2026-03-01", time: "morning" });
    expect(() => createEntity(created.root, { kind: "chapter", name: "Bad Date", number: 2, date: "yesterday" })).toThrow("YYYY-MM-DD");
    expect(() => createEntity(created.root, { kind: "chapter", name: "Bad Time", number: 2, time: "99:99" })).toThrow("HH:MM");
    expect(() => createEntity(created.root, { kind: "chapter", name: "Short Hour", number: 2, time: "1:00" })).toThrow("HH:MM");
    expect(() => createEntity(created.root, { kind: "scene", name: "Back", chapter: "chapter-01", scene: 1, "travel-hours": -1 })).toThrow("zero or positive");
    expect(() => createEntity(created.root, { kind: "scene", name: "Bad Date", chapter: "chapter-01", scene: 2, date: "yesterday" })).toThrow("YYYY-MM-DD");
    expect(() => createEntity(created.root, { kind: "scene", name: "Bad Time", chapter: "chapter-01", scene: 2, time: "99:99" })).toThrow("HH:MM");
  });

  test("accepts two relationship types between the same pair", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Two Links", force: false });
    writeMarkdown(path.join(created.root, "characters", "ada.md"), `
name: Ada
role: protagonist
status: alive
relationships:
  - character: bea
    type: parent
  - character: bea
    type: friend
`, "# Ada");
    writeMarkdown(path.join(created.root, "characters", "bea.md"), `
name: Bea
role: supporting
status: alive
relationships:
  - character: ada
    type: friend
  - character: ada
    type: child
`, "# Bea");

    expect(validateLinks(created.root).ok).toBe(true);
  });

  test("accepts either gendered inverse for aunt, uncle, niece, and nephew", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Mixed Kin", force: false });
    writeMarkdown(path.join(created.root, "characters", "ada.md"), `
name: Ada
role: protagonist
status: alive
relationships:
  - character: bea
    type: uncle
  - character: cal
    type: aunt
`, "# Ada");
    writeMarkdown(path.join(created.root, "characters", "bea.md"), `
name: Bea
role: supporting
status: alive
relationships:
  - character: ada
    type: niece
`, "# Bea");
    writeMarkdown(path.join(created.root, "characters", "cal.md"), `
name: Cal
role: supporting
status: alive
relationships:
  - character: ada
    type: nephew
`, "# Cal");
    expect(validateLinks(created.root).errors).toEqual([]);

    writeMarkdown(path.join(created.root, "characters", "cal.md"), `
name: Cal
role: supporting
status: alive
relationships:
  - character: ada
    type: friend
`, "# Cal");
    expect(validateLinks(created.root).errors.join("\n")).toContain("relationship aunt to cal expects backlink type nephew or niece, got friend");
  });

  test("covers helper errors, fallback branches, and malformed continuity state", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Coverage Branches", force: false });
    expect(() => createEntity(created.root, { kind: "character", name: "" })).toThrow("name is required");
    expect(() => createEntity(created.root, { kind: "beast", name: "Wolf" })).toThrow("Unsupported entity kind");
    createEntity(created.root, { kind: "glossary", name: "Moon Gate" });
    createEntity(created.root, { kind: "character", name: "Branch Person", location: "missing-location" });
    createEntity(created.root, { kind: "location", name: "Branch Place", character: "missing-person" });
    expect(() => createEntity(created.root, { kind: "location", name: "Branch Place" })).toThrow("already exists");
    expect(() => renameEntity(created.root, { kind: "character", id: "", name: "Nope" })).toThrow("rename requires");
    expect(() => renameEntity(created.root, { kind: "character", id: "missing-person", name: "Nope" })).toThrow("does not exist");
    createEntity(created.root, { kind: "character", name: "Other Person" });
    expect(() => renameEntity(created.root, { kind: "character", id: "branch-person", name: "Other Person" })).toThrow("already exists");
    expect(() => removeEntity(created.root, { kind: "character", id: "" })).toThrow("remove requires");
    expect(() => removeEntity(created.root, { kind: "character", id: "missing-person" })).toThrow("does not exist");
    expect(() => buildBook(created.root, { format: "epub" })).toThrow("No chapters found to export");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: Stale
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 99
`, "## Chapter Text\n\nOne.");
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-01.md"), `
title: Optional State
chapter: chapter-01
scene: 1
status: draft
`, "# Optional State");
    expect(createEntity(created.root, { kind: "chapter", name: "Auto Numbered" }).id).toBe("chapter-02");
    expect(formatActionReport(projectActions(created.root))).toContain("Refresh word counts");

    fs.writeFileSync(
      path.join(created.root, "continuity", "state.md"),
      fs.readFileSync(path.join(created.root, "continuity", "state.md"), "utf8")
        .replace("type: continuity-state", "type: wrong-state")
        .replace("story: coverage-branches", "story: wrong-story")
        .replace("character-state: []", "character-state: none"),
      "utf8"
    );
    writeMarkdown(path.join(created.root, "scenes", "bad-state.md"), `
title: Bad State
chapter: chapter-01
scene: 1
status: draft
state-changes: none
`, "# Bad State");

    const validation = validateProject(created.root);
    expect(validation.errors.join("\n")).toContain("continuity/state.md type must be continuity-state");
    expect(validation.errors.join("\n")).toContain("continuity/state.md story must be coverage-branches");
    expect(validation.errors.join("\n")).toContain("continuity/state.md frontmatter field character-state must be a list");
    expect(validation.errors.join("\n")).toContain("scenes/bad-state.md frontmatter field state-changes must be a list");

    const actions = formatActionReport(projectActions(created.root));
    expect(actions).toContain("Fix validation errors");
    expect(actions).toContain("Fix broken references");
  });

  test("validates v2 entity frontmatter and reference contracts", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "V2 Broken", force: false });
    writeMarkdown(path.join(created.root, "worldbuilding", "factions", "bad-faction.md"), `
name: Bad Faction
type: guild
status: active
members:
  - missing-person
locations:
  - missing-place
tags: []
`, "# Bad Faction");
    writeMarkdown(path.join(created.root, "worldbuilding", "artifacts", "bad-artifact.md"), `
name: Bad Artifact
type: relic
status: active
owner: missing-owner
location: missing-place
tags: []
`, "# Bad Artifact");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 1
`, "## Chapter Text\n\nOne.");
    writeMarkdown(path.join(created.root, "scenes", "bad-scene.md"), `
title: Bad Scene
chapter: missing-chapter
scene: 0
pov: missing-person
location: missing-place
characters:
  - missing-person
arcs-advanced:
  - missing-arc
status: invalid
state-changes:
  - not-object
`, "# Bad Scene");
    writeMarkdown(path.join(created.root, "continuity", "questions", "bad-question.md"), `
title: Bad Question
status: invalid
introduced: missing-chapter
resolved: missing-chapter
characters:
  - missing-person
`, "# Bad Question");
    writeMarkdown(path.join(created.root, "continuity", "promises", "bad-promise.md"), `
title: Bad Promise
status: invalid
planted: missing-chapter
payoff: missing-chapter
arcs:
  - missing-arc
characters:
  - missing-person
`, "# Bad Promise");
    writeMarkdown(path.join(created.root, "glossary", "terms", "bad-term.md"), `
term: Bad Term
category: invalid
aliases:
  - ""
`, "# Bad Term");

    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors.join("\n")).toContain("scenes/bad-scene.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("scenes/bad-scene.md scene must be greater than 0");
    expect(validation.errors.join("\n")).toContain("continuity/questions/bad-question.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("continuity/promises/bad-promise.md frontmatter field status has unsupported value invalid");
    expect(validation.errors.join("\n")).toContain("glossary/terms/bad-term.md frontmatter field category has unsupported value invalid");

    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("bad-faction.md references missing member missing-person");
    expect(links.errors.join("\n")).toContain("bad-artifact.md references missing owner missing-owner");
    expect(links.errors.join("\n")).toContain("bad-scene.md references missing chapter missing-chapter");
    expect(links.errors.join("\n")).toContain("bad-question.md references missing character missing-person");
    expect(links.errors.join("\n")).toContain("bad-promise.md references missing arc missing-arc");
  });

  test("reports numeric scene chapter ids as link errors instead of crashing scans", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Numeric Chapter", force: false });
    const chapters = ["chapter-02", "3", "chapter-01", "chapter-04", "chapter-03"];
    chapters.forEach((chapter, index) => {
      writeMarkdown(path.join(created.root, "scenes", `${String.fromCharCode(97 + index)}-scene.md`), `
title: Scene ${index + 1}
chapter: ${chapter}
scene: 1
status: draft
`, `# Scene ${index + 1}`);
    });

    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("scenes/b-scene.md references missing chapter 3");
  });

  test("builds epub and docx formats and rejects unknown formats", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Plain Build", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
pov: ""
locations: []
characters: []
arcs-advanced: []
status: draft
word-count: 0
`, "## Chapter Text\n\nOne.\n\n---\n\nTwo.");

    const epub = buildBook(created.root, { format: "epub" });
    const docx = buildBook(created.root, { format: "docx" });
    expect(epub).toEqual({
      outFile: path.join(created.root, "dist", "plain-build.epub"),
      chapters: 1,
      format: "epub"
    });
    expect(docx).toEqual({
      outFile: path.join(created.root, "dist", "plain-build.docx"),
      chapters: 1,
      format: "docx"
    });
    expect(fs.readFileSync(epub.outFile).readUInt32LE(0)).toBe(0x04034b50);
    expect(fs.readFileSync(epub.outFile).toString("utf8")).toContain("dcterms:modified");
    expect(fs.readFileSync(epub.outFile).toString("utf8")).toContain("<p>* * *</p>");
    expect(fs.readFileSync(docx.outFile).toString("utf8")).toContain("word/document.xml");
    expect(fs.readFileSync(docx.outFile).toString("utf8")).toContain("word/styles.xml");
    expect(fs.readFileSync(docx.outFile).toString("utf8")).toContain('<w:t xml:space="preserve">* * *</w:t>');
    expect(() => buildBook(created.root, { format: "pdf" })).toThrow("Unsupported build format: pdf");
  });

  test("falls back to filename scene numbers without throwing", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Scene Fallback", force: false });
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-03.md"), `
title: No Scene Key
chapter: chapter-01
status: draft
`, "# No Scene Key");
    const project = scanProject(created.root);
    expect(project.scenes[0].scene).toBe(3);
    const validation = validateProject(created.root);
    expect(validation.errors.join("\n")).toContain("scenes/chapter-01-scene-03.md is missing frontmatter field scene");
  });

  test("converts missing or invalid frontmatter into per-file errors", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Frontmatter Gaps", force: false });
    fs.writeFileSync(path.join(created.root, "characters", "broken.md"), "# No frontmatter\n", "utf8");
    fs.writeFileSync(path.join(created.root, "chapters", "chapter-01.md"), "---\ntitle: Bad\n: oops\n---\nBody\n", "utf8");
    const validation = validateProject(created.root);
    expect(validation.ok).toBe(false);
    expect(validation.errors.join("\n")).toContain("characters/broken.md");
    expect(validation.errors.join("\n")).toContain("chapters/chapter-01.md");
    const links = validateLinks(created.root);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("characters/broken.md");
    expect(() => reindexProject(created.root)).not.toThrow();
  });

  test("anchors chapter filenames and enforces scene patterns with duplicate detection", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Filename Patterns", force: false });
    writeMarkdown(path.join(created.root, "chapters", "my-chapter-01-notes.md"), `
title: Notes
number: 1
status: draft
word-count: 0
`, "# Notes");
    writeMarkdown(path.join(created.root, "scenes", "random.md"), `
title: Random
chapter: chapter-01
scene: 1
status: draft
`, "# Random");
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-01.md"), `
title: First
chapter: chapter-01
scene: 1
status: draft
`, "# First");
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-01-dup.md"), `
title: Dup
chapter: chapter-01
scene: 1
status: draft
`, "# Dup");
    const validation = validateProject(created.root);
    expect(validation.errors.join("\n")).toContain("my-chapter-01-notes.md filename must match chapter-{NN}.md");
    expect(validation.errors.join("\n")).toContain("scenes/random.md filename must match {chapter}-scene-{NN}.md");
    expect(validation.errors.join("\n")).toContain("duplicates scene 1 of chapter-01");
  });

  test("rejects non-string enum values and scalar lists surface in links", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Enum Lists", force: false });
    writeMarkdown(path.join(created.root, "characters", "numeric-status.md"), `
name: Numeric
role: supporting
status: 123
locations: []
`, "# Numeric");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
status: draft
characters: lone-wolf
word-count: 0
`, "# One");
    const validation = validateProject(created.root);
    expect(validation.errors.join("\n")).toContain("numeric-status.md frontmatter field status has unsupported value 123");
    expect(validation.errors.join("\n")).toContain("chapter-01.md frontmatter field characters must be a list");
    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("lone-wolf");
  });

  test("warns on stray top-level files and nested entity files", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Stray Files", force: false });
    fs.writeFileSync(path.join(created.root, "notes.md"), "# stray\n", "utf8");
    writeMarkdown(path.join(created.root, "characters", "extra", "nested.md"), `
name: Nested
role: supporting
status: alive
`, "# Nested");
    const validation = validateProject(created.root);
    expect(validation.warnings.join("\n")).toContain("notes.md is not part of the story project model and is ignored");
    expect(validation.warnings.join("\n")).toContain("nested inside an entity directory and is ignored");
  });

  test("validates flashback-to, episode-question, time-skip, and story craft fields", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Craft Fields", force: false });
    const root = created.root;

    writeMarkdown(path.join(root, "chapters", "chapter-01.md"), `
title: One
number: 1
status: draft
mode: discovered
episode-question: Will Mara escape?
time-skip: Day 1 → Day 10
word-count: 0
`, "## Chapter Text\n\nWords here.\n");
    writeMarkdown(path.join(root, "scenes", "chapter-01-scene-01.md"), `
title: Opening
chapter: chapter-01
scene: 1
status: draft
flashback-to: chapter-01
`, "# Opening\n");
    const storyPath = path.join(root, "story.md");
    const storyRaw = fs.readFileSync(storyPath, "utf8");
    fs.writeFileSync(storyPath, storyRaw
      .replace("status: planning", "status: planning\nseason-goal: Take the city\ntarget-words: 80000\ndraft-mode: discovered"), "utf8");

    const project = scanProject(root);
    expect(project.scenes[0].flashbackTo).toBe("chapter-01");

    const validation = validateProject(root);
    expect(validation.errors.filter((error) => error.includes("flashback-to"))).toEqual([]);
    expect(validation.errors.filter((error) => error.includes("episode-question"))).toEqual([]);
    expect(validation.errors.filter((error) => error.includes("time-skip"))).toEqual([]);
    expect(validation.errors.filter((error) => error.includes("season-goal"))).toEqual([]);
    expect(validation.errors.filter((error) => error.includes("target-words"))).toEqual([]);
    expect(validation.errors.filter((error) => error.includes("draft-mode"))).toEqual([]);
  });

  test("rejects non-scalar craft fields and non-integer target-words", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Bad Craft Fields", force: false });
    const root = created.root;

    writeMarkdown(path.join(root, "chapters", "chapter-01.md"), `
title: One
number: 1
status: draft
episode-question:
  - not-a-scalar
time-skip:
  - not-a-scalar
word-count: 0
`, "## Chapter Text\n\nWords here.\n");
    writeMarkdown(path.join(root, "scenes", "chapter-01-scene-01.md"), `
title: Opening
chapter: chapter-01
scene: 1
status: draft
flashback-to:
  - not-a-scalar
`, "# Opening\n");
    const storyPath = path.join(root, "story.md");
    const storyRaw = fs.readFileSync(storyPath, "utf8");
    fs.writeFileSync(storyPath, storyRaw
      .replace("status: planning", "status: planning\nseason-goal:\n  - not-a-scalar\ntarget-words: many\ndraft-mode:\n  - not-a-scalar"), "utf8");

    const result = validateProject(root);
    expect(result.ok).toBe(false);
    expect(result.errors).toContain("scenes/chapter-01-scene-01.md frontmatter field flashback-to must be a scalar");
    expect(result.errors).toContain("chapters/chapter-01.md frontmatter field episode-question must be a scalar");
    expect(result.errors).toContain("chapters/chapter-01.md frontmatter field time-skip must be a scalar");
    expect(result.errors).toContain("story.md frontmatter field season-goal must be a scalar");
    expect(result.errors).toContain("story.md frontmatter field target-words must be an integer");
    expect(result.errors).toContain("story.md frontmatter field draft-mode must be a scalar");
  });

  test("coerces numeric chapter refs to strings and guards next chapter number", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Numeric Refs", force: false });
    writeMarkdown(path.join(created.root, "continuity", "questions", "q.md"), `
title: Q
status: open
introduced: 1
resolved: 2
characters: []
`, "# Q");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: Broken Number
number: many
status: draft
word-count: 0
`, "# Broken");
    const project = scanProject(created.root);
    expect(typeof project.questions[0].introduced).toBe("string");
    expect(project.questions[0].introduced).toBe("1");
    const actions = projectActions(created.root);
    expect(JSON.stringify(actions.actions)).not.toContain("NaN");
  });

  test("refuses duplicate chapter numbers and builds deterministically", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Deterministic Build", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
status: draft
word-count: 0
`, "## Chapter Text\n\nOne.");
    writeMarkdown(path.join(created.root, "chapters", "chapter-02.md"), `
title: Two
number: 1
status: draft
word-count: 0
`, "## Chapter Text\n\nTwo.");
    expect(() => buildBook(created.root, { format: "epub" })).toThrow("Duplicate chapter number 1");
    fs.rmSync(path.join(created.root, "chapters", "chapter-02.md"));
    const first = buildBook(created.root, { format: "epub", out: "dist/first.epub" });
    const second = buildBook(created.root, { format: "epub", out: "dist/second.epub" });
    expect(fs.readFileSync(first.outFile).equals(fs.readFileSync(second.outFile))).toBe(true);
    expect(fs.readFileSync(first.outFile).toString("utf8")).toContain("2000-01-01T00:00:00Z");
    process.env.SOURCE_DATE_EPOCH = "1234567890";
    try {
      const dated = buildBook(created.root, { format: "epub", out: "dist/dated.epub" });
      expect(fs.readFileSync(dated.outFile).toString("utf8")).toContain("2009-02-13T23:31:30Z");
    } finally {
      delete process.env.SOURCE_DATE_EPOCH;
    }
  });

  test("reindex refreshes timeline and continuity story fields on title change", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Original Title", force: false });
    fs.writeFileSync(
      path.join(created.root, "story.md"),
      fs.readFileSync(path.join(created.root, "story.md"), "utf8").replace("Original Title", "Renamed Title"),
      "utf8"
    );
    const reindexed = reindexProject(created.root);
    expect(reindexed.changed.join("\n")).toContain("timeline.md");
    expect(reindexed.changed.join("\n")).toContain("state.md");
    expect(scanProject(created.root).storyId).toBe("renamed-title");
    expect(fs.readFileSync(path.join(created.root, "plot", "timeline.md"), "utf8")).toContain("story: renamed-title");
    expect(fs.readFileSync(path.join(created.root, "continuity", "state.md"), "utf8")).toContain("story: renamed-title");
  });

  test("kebab-validates id refs, checks died-in, and follows timeline tokens", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Link Formats", force: false });
    writeMarkdown(path.join(created.root, "characters", "hero.md"), `
name: Hero
role: protagonist
status: alive
died-in: missing-chapter
locations: []
`, "# Hero");
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
status: draft
characters:
  - Bad_ID
word-count: 0
`, "# One");
    fs.appendFileSync(path.join(created.root, "plot", "timeline.md"), "\n| Day 1 | Lost event | Arc | chapter-99 |\n", "utf8");
    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("Bad_ID which must be kebab-case");
    expect(links.errors.join("\n")).toContain("hero.md references missing chapter missing-chapter");
    expect(links.errors.join("\n")).toContain("timeline.md");
  });

  test("writes mentions for new chapters and scenes and wires character arc", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Mentions Arc", force: false });
    createEntity(created.root, { kind: "character", name: "Mira Sol", role: "protagonist" });
    const chapter = createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1, mentions: "mira-sol" });
    const scene = createEntity(created.root, { kind: "scene", name: "Pier", chapter: "chapter-01", mentions: ["mira-sol"] });
    expect(fs.readFileSync(chapter.file, "utf8")).toContain("mentions:");
    expect(fs.readFileSync(chapter.file, "utf8")).toContain("mira-sol");
    expect(fs.readFileSync(scene.file, "utf8")).toContain("mira-sol");
    const arcCharacter = createEntity(created.root, { kind: "character", name: "Arc Hero", arc: "redemption" });
    expect(fs.readFileSync(arcCharacter.file, "utf8")).toContain("arc:");
    expect(scanProject(created.root).characters.find((item) => item.id === "arc-hero").arc).toBe("redemption");
    expect(validateProject(created.root).ok).toBe(true);
  });
});

describe("ingest and link hardening", () => {
  test("surfaces story.md frontmatter errors instead of crashing", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Broken Story", force: false });
    fs.writeFileSync(
      path.join(created.root, "story.md"),
      "---\ntitle: Broken\ntitle: Twice\n---\n# Broken\n",
      "utf8"
    );
    const result = validateProject(created.root);
    expect(result.errors.join("\n")).toContain("story.md: Duplicate frontmatter key: title");
  });

  test("surfaces continuity state frontmatter errors instead of crashing", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Broken State", force: false });
    fs.writeFileSync(
      path.join(created.root, "continuity", "state.md"),
      "---\ntype: continuity-state\ntype: twice\n---\n# State\n",
      "utf8"
    );
    const result = validateProject(created.root);
    expect(result.errors.join("\n")).toContain("continuity/state.md: Duplicate frontmatter key: type");
  });

  test("surfaces entity frontmatter errors instead of crashing", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Broken Entity", force: false });
    writeMarkdown(path.join(created.root, "characters", "bad.md"), `
name: Bad
name: Twice
role: supporting
status: alive
`, "# Bad\n");
    const result = validateProject(created.root);
    expect(result.errors.join("\n")).toContain("characters/bad.md: Duplicate frontmatter key: name");
  });

  test("rejects non-kebab-case link targets without crashing", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Kebab Links", force: false });
    writeMarkdown(path.join(created.root, "chapters", "chapter-01.md"), `
title: One
number: 1
pov: Mira Sol
status: draft
word-count: 0
`, "## Chapter Text\n\nOne two.");
    writeMarkdown(path.join(created.root, "worldbuilding", "artifacts", "odd-relic.md"), `
name: Odd Relic
type: object
status: active
owner: Bad Owner
`, "# Odd Relic\n");
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-01.md"), `
title: Opener
chapter: Chapter 01
scene: 1
pov: Mira Sol
status: draft
`, "# Opener\n");
    writeMarkdown(path.join(created.root, "worldbuilding", "factions", "quiet-ones.md"), `
name: Quiet Ones
type: guild
status: active
members:
  - ""
`, "# Quiet Ones\n");
    const links = validateLinks(created.root);
    const output = links.errors.join("\n");
    expect(output).toContain("references POV character Mira Sol which must be kebab-case");
    expect(output).toContain("references owner Bad Owner which must be kebab-case");
    expect(output).toContain("references chapter Chapter 01 which must be kebab-case");
    expect(output).not.toContain("member");
  });

  test("checks timeline and arc body references", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Body Refs", force: false });
    createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1 });
    fs.writeFileSync(path.join(created.root, "plot", "notes.md"), "# Notes\n", "utf8");
    fs.appendFileSync(
      path.join(created.root, "plot", "timeline.md"),
      "\nSee [Ghost Ship](ghost-ship.md), [Bad Name](Bad Name.md), [Web](https://example.com/x), [Img](map.png), [Idx](characters/_index.md), [Query](?q=1), [Missing Dir](does-not-exist/harbor.md), [Notes](notes.md), and [Part](../chapters/chapter-01.md#text).\n",
      "utf8"
    );
    const arc = createEntity(created.root, { kind: "arc", name: "Lost Arc" });
    fs.appendFileSync(arc.file, "\nThe trail ends in chapter-99. See [Lost](lost-thing.md).\n", "utf8");
    const links = validateLinks(created.root);
    const output = links.errors.join("\n");
    expect(output).toContain("links to missing file ghost-ship.md");
    expect(output).toContain("links to Bad Name.md which must be kebab-case");
    expect(output).toContain("references missing chapter chapter-99");
    expect(output).toContain("links to missing file lost-thing.md");
    expect(output).toContain("links to missing file does-not-exist/harbor.md");
    expect(output).toContain("links to missing file notes.md");
    expect(output).not.toContain("chapter-01.md#text");
    expect(output).not.toContain("example.com");
    expect(output).not.toContain("map.png");
    expect(output).not.toContain("_index.md");
  });

  test("surfaces registry frontmatter errors instead of crashing", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Broken Index", force: false });
    fs.writeFileSync(
      path.join(created.root, "plot", "_index.md"),
      "---\ntype: plot-registry\ntype: twice\n---\n# Plot\n",
      "utf8"
    );
    const result = validateProject(created.root);
    expect(result.errors.join("\n")).toContain("plot/_index.md: Duplicate frontmatter key: type");
  });

  test("surfaces timeline frontmatter errors during link checks", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Broken Timeline", force: false });
    fs.writeFileSync(
      path.join(created.root, "plot", "timeline.md"),
      "---\nstory: broken\nstory: twice\n---\n# Timeline\n",
      "utf8"
    );
    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("plot/timeline.md: Duplicate frontmatter key: story");
  });

  test("reindex tolerates registry and timeline file problems", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Tough Reindex", force: false });
    const plotIndex = path.join(created.root, "plot", "_index.md");
    const timeline = path.join(created.root, "plot", "timeline.md");
    fs.writeFileSync(plotIndex, "---\ntitle: Tough\ntitle: Twice\n---\n# Plot\n", "utf8");
    expect(() => reindexProject(created.root)).toThrow("Duplicate frontmatter key: title");
    fs.writeFileSync(plotIndex, "---\nstory: tough-reindex\nstructure: three-act\n---\n# Plot\n", "utf8");
    expect(reindexProject(created.root).changed).toBeDefined();
    fs.rmSync(timeline);
    expect(reindexProject(created.root).changed).toBeDefined();
    fs.mkdirSync(timeline);
    expect(reindexProject(created.root).changed).toBeDefined();
    fs.rmSync(timeline, { recursive: true });
    fs.writeFileSync(timeline, "---\nstory: tough\nstory: twice\n---\n# Timeline\n", "utf8");
    expect(reindexProject(created.root).changed).toBeDefined();
  });

  test("flags scene frontmatter that disagrees with the filename", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Scene Names", force: false });
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-01.md"), `
title: Opener
chapter: chapter-02
scene: 2
status: draft
`, "# Opener\n");
    const result = validateProject(created.root);
    const output = result.errors.join("\n");
    expect(output).toContain("chapter must match filename chapter chapter-01");
    expect(output).toContain("scene must match filename scene number 1");
  });

  test("requires the continuity state file", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "No State", force: false });
    createEntity(created.root, { kind: "character", name: "Mira Sol", role: "protagonist" });
    createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1, mentions: "mira-sol" });
    fs.rmSync(path.join(created.root, "continuity", "state.md"));
    const result = validateProject(created.root);
    expect(result.ok).toBe(false);
    expect(result.errors).toContain("Missing required path: continuity/state.md");
  });

  test("falls back to the filename chapter for chapterless scenes", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Chapterless", force: false });
    writeMarkdown(path.join(created.root, "scenes", "chapter-01-scene-09.md"), `
title: Aside
scene: 9
status: draft
`, "# Aside\n");
    const scene = scanProject(created.root).scenes.find((item) => item.id === "chapter-01-scene-09");
    expect(scene.chapter).toBe("chapter-01");
  });

  test("falls back to the default timestamp for non-numeric SOURCE_DATE_EPOCH", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Epoch", force: false });
    createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1 });
    const previous = process.env.SOURCE_DATE_EPOCH;
    process.env.SOURCE_DATE_EPOCH = "not-a-number";
    try {
      const built = buildBook(created.root, { format: "epub" });
      expect(fs.existsSync(built.outFile)).toBe(true);
    } finally {
      if (previous === undefined) {
        delete process.env.SOURCE_DATE_EPOCH;
      } else {
        process.env.SOURCE_DATE_EPOCH = previous;
      }
    }
  });

  test("scans multiple entities of every kind", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Kitchen Sink", force: false });
    createEntity(created.root, { kind: "character", name: "Alpha Hero", role: "protagonist" });
    createEntity(created.root, { kind: "character", name: "Beta Rival", role: "antagonist" });
    createEntity(created.root, { kind: "location", name: "North Gate", type: "city" });
    createEntity(created.root, { kind: "location", name: "South Field", type: "wilderness" });
    createEntity(created.root, { kind: "system", name: "Old Magic", type: "magic" });
    createEntity(created.root, { kind: "system", name: "New Tech", type: "technology" });
    createEntity(created.root, { kind: "faction", name: "Red Guild", type: "guild" });
    createEntity(created.root, { kind: "faction", name: "Blue Court", type: "government" });
    createEntity(created.root, { kind: "artifact", name: "Sun Blade", type: "weapon" });
    createEntity(created.root, { kind: "artifact", name: "Moon Coin", type: "object" });
    createEntity(created.root, { kind: "arc", name: "First Arc", type: "main" });
    createEntity(created.root, { kind: "arc", name: "Second Arc", type: "subplot" });
    createEntity(created.root, { kind: "chapter", name: "Arrival", number: 1 });
    createEntity(created.root, { kind: "chapter", name: "Departure", number: 2 });
    createEntity(created.root, { kind: "scene", name: "Pier", chapter: "chapter-01", scene: 1 });
    createEntity(created.root, { kind: "scene", name: "Gate", chapter: "chapter-01", scene: 2 });
    createEntity(created.root, { kind: "question", name: "Who Knocked" });
    createEntity(created.root, { kind: "question", name: "Who Answered" });
    createEntity(created.root, { kind: "promise", name: "First Promise" });
    createEntity(created.root, { kind: "promise", name: "Second Promise" });
    createEntity(created.root, { kind: "term", name: "First Term" });
    createEntity(created.root, { kind: "term", name: "Second Term" });
    const project = scanProject(created.root);
    expect(project.characters.length).toBe(2);
    expect(project.locations.length).toBe(2);
    expect(project.systems.length).toBe(2);
    expect(project.factions.length).toBe(2);
    expect(project.artifacts.length).toBe(2);
    expect(project.arcs.length).toBe(2);
    expect(project.chapters.length).toBe(2);
    expect(project.scenes.length).toBe(2);
    expect(project.questions.length).toBe(2);
    expect(project.promises.length).toBe(2);
    expect(project.glossaryTerms.length).toBe(2);
    // A body link forces checkBodyLinkTarget to build its known-id set over
    // every non-empty collection.
    fs.appendFileSync(
      path.join(created.root, "plot", "timeline.md"),
      "\nSee [Ghost Ship](ghost-ship.md).\n",
      "utf8"
    );
    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("links to missing file ghost-ship.md");
  });
});

describe("review-findings hardening", () => {
  test("body links that resolve through a symlink to outside the project fail", () => {
    const cwd = makeTempDir();
    const created = createStoryProject({ cwd, title: "Escaping Link", force: false });
    createEntity(created.root, { kind: "character", name: "Mara", role: "protagonist" });
    const outside = path.join(cwd, "mara.md");
    fs.writeFileSync(outside, "# Outside\n", "utf8");
    fs.mkdirSync(path.join(created.root, "plot", "notes"));
    try {
      fs.symlinkSync(outside, path.join(created.root, "plot", "notes", "mara.md"));
    } catch {
      console.warn("Skipping body-link symlink test: symlinks unavailable.");
      return;
    }
    fs.appendFileSync(path.join(created.root, "plot", "timeline.md"), "\nSee [Mara](notes/mara.md).\n", "utf8");

    const links = validateLinks(created.root);
    expect(links.errors.join("\n")).toContain("plot/timeline.md links to notes/mara.md which resolves outside the project");
  });

  test("init refuses a symlinked project directory even with force", () => {
    const cwd = makeTempDir();
    fs.mkdirSync(path.join(cwd, "real"));
    try {
      fs.symlinkSync(path.join(cwd, "real"), path.join(cwd, "linked"), "dir");
    } catch {
      console.warn("Skipping symlinked init test: symlinks unavailable.");
      return;
    }
    expect(() => createStoryProject({ cwd, title: "Linked", dir: "linked", force: true })).toThrow("symlinked project directory");
    expect(fs.readdirSync(path.join(cwd, "real"))).toEqual([]);
  });

  test("arc body re-read failures become structured errors instead of throwing", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Arc Errors", cwd }).root;
    const created = createEntity(root, { kind: "arc", name: "Broken Arc" });
    expect(created.id).toBe("broken-arc");
    const project = scanProject(root);
    expect(project.arcs.length).toBe(1);
    fs.writeFileSync(created.file, "no frontmatter here\n", "utf8");
    const links = validateLinksOf(project);
    expect(links.ok).toBe(false);
    expect(links.errors.join("\n")).toContain("plot/arcs/broken-arc.md");
  });

  test("validateProjectOf and validateLinksOf match the scanning wrappers", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Single Scan", cwd }).root;
    const scanned = scanProject(root);
    expect(validateProjectOf(scanned)).toEqual(validateProject(root));
    expect(validateLinksOf(scanned)).toEqual(validateLinks(root));
    const reported = projectReport(root);
    expect(reported.validation).toEqual(validateProject(root));
    expect(reported.links).toEqual(validateLinks(root));
    const actions = projectActions(root);
    expect(actions.validation).toEqual(validateProject(root));
    expect(actions.links).toEqual(validateLinks(root));
  });

  test("reindex propagates a corrupt plot index instead of resetting to three-act", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Reindex Errors", cwd }).root;
    fs.writeFileSync(path.join(root, "plot", "_index.md"), "no frontmatter\n", "utf8");
    expect(() => reindexProject(root)).toThrow("missing YAML frontmatter");
    fs.rmSync(path.join(root, "plot", "_index.md"));
    const rebuilt = reindexProject(root);
    expect(rebuilt.changed.join("\n")).toContain("_index.md");
    expect(fs.readFileSync(path.join(root, "plot", "_index.md"), "utf8")).toContain("three-act");
  });

  test("createStoryProject rejects titles with no usable story id", () => {
    const cwd = makeTempDir();
    const before = fs.readdirSync(cwd);
    expect(() => createStoryProject({ title: "!!!", cwd })).toThrow("Cannot derive a story id");
    expect(() => createStoryProject({ title: "!!!", cwd, dir: "punctuated" })).toThrow("Cannot derive a story id");
    expect(fs.readdirSync(cwd)).toEqual(before);
  });

  test("oversized entity files surface as scan errors instead of being read", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Big Files", cwd }).root;
    const big = "x".repeat(6 * 1024 * 1024);
    fs.writeFileSync(path.join(root, "chapters", "chapter-99.md"), big, "utf8");
    const project = scanProject(root);
    expect(project.fileErrors.join("\n")).toContain("oversized");
    expect(validateProject(root).errors.join("\n")).toContain("oversized");
  });

  test("scan refuses entity directories packed past the file cap", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Packed", cwd }).root;
    for (let i = 0; i < 5001; i++) {
      fs.writeFileSync(path.join(root, "characters", `extra-${i}.md`), "# Extra\n", "utf8");
    }
    expect(() => scanProject(root)).toThrow("exceeds the 5000 file limit");
  });

  test("rename refuses to scan past the directory depth cap", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Deep", cwd }).root;
    writeMarkdown(path.join(root, "characters", "deep-char.md"), `
name: "Deep Char"
role: supporting
status: alive
`, "# Deep\n");
    let dir = path.join(root, "notes");
    for (let i = 0; i < 12; i++) {
      dir = path.join(dir, `level-${i}`);
    }
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "note.md"), "# Deep note\n", "utf8");
    expect(() => renameEntity(root, { kind: "character", id: "deep-char", name: "Deeper Char" })).toThrow("beyond depth 10");
  });

  test("rename refuses to scan past the file count cap", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Many", cwd }).root;
    writeMarkdown(path.join(root, "characters", "many-char.md"), `
name: "Many Char"
role: supporting
status: alive
`, "# Many\n");
    const dir = path.join(root, "notes");
    fs.mkdirSync(dir, { recursive: true });
    for (let i = 0; i < 5001; i++) {
      fs.writeFileSync(path.join(dir, `note-${i}.md`), "# Note\n", "utf8");
    }
    expect(() => renameEntity(root, { kind: "character", id: "many-char", name: "Many Char Two" })).toThrow("exceeds the 5000 file limit");
  });

  test("scan tolerates size-stat failures during project scan", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Gone", cwd }).root;
    const originalStatSync = fs.statSync;
    fs.statSync = () => { throw new Error("ENOENT: gone"); };
    try {
      const project = scanProject(root);
      expect(project.root).toBe(path.resolve(root));
    } finally {
      fs.statSync = originalStatSync;
    }
  });

  test("createEntity rejects unsupported enum values", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Enums", cwd }).root;
    expect(() => createEntity(root, { kind: "character", name: "Bad Role", role: "emperor" })).toThrow(
      'Unsupported character role "emperor"'
    );
    expect(() => createEntity(root, { kind: "term", name: "Bad Cat", category: "bogus" })).toThrow(
      'Unsupported term category "bogus"'
    );
    expect(() => createEntity(root, { kind: "clue", name: "Bad Status", status: "bogus" })).toThrow(
      'Unsupported clue status "bogus"'
    );
    const ok = createEntity(root, { kind: "character", name: "Good Role", role: "protagonist" });
    expect(ok.id).toBe("good-role");
  });

  test("projectReport and projectActions flag missing required paths", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Partial", cwd }).root;
    fs.rmSync(path.join(root, "scenes"), { recursive: true, force: true });
    const report = projectReport(root);
    expect(report.validation.ok).toBe(false);
    expect(report.validation.errors.join("\n")).toContain("Missing required path:");
    const actions = projectActions(root);
    expect(actions.validation.ok).toBe(false);
    expect(actions.validation.errors.join("\n")).toContain("Missing required path:");
  });

  test("validateProjectOf matches validateProject on a valid project", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Even", cwd }).root;
    expect(validateProjectOf(scanProject(root))).toEqual(validateProject(root));
  });

  test("oversized registry indexes surface as validation errors", () => {
    const cwd = makeTempDir();
    const root = createStoryProject({ title: "Big Index", cwd }).root;
    fs.writeFileSync(path.join(root, "characters", "_index.md"), "x".repeat(6 * 1024 * 1024), "utf8");
    const errors = validateProject(root).errors.join("\n");
    expect(errors).toContain(path.join("characters", "_index.md"));
    expect(errors).toContain("exceeds the");
  });
});
